
volumes:
  postgres_data:
    
services:
  app:
    container_name: library_app
    image: library:latest
    build: 
      context: ../../ovozber_project
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ../../api_library:/app
    ports:
      - 8018:8018
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: ../.env

  db:
    container_name: library_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ../.env.db
